### ISSUE TITLE
Behavior for payment manifests

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/webappsec-fetch-metadata#30]
From https://crbug.com/966507 :

When `X.com` causes Chrome to download `Y.com` and, after Chrome parses the data from `Y.com`, Chrome finds in there another URL that it needs to fetch, should the `request_initiator` be `X.com` or `Y.com`?

This happens because Chrome implements https://w3c.github.io/payment-method-manifest/#fetch-pmm , which can cause the following interaction, for example:

1. A merchant website calls
   ```javascript
   new PaymentRequest([{supportedOrigins: 'http://google.com/pay'}],
      {total: {label: 'Total', amount: {value: '1.00', currency: 'USD'}}});
   ```
1. Chrome performs `HEAD  https://google.com/pay`, which 303 redirects to `HEAD  https://pay.google.com/about`
    * https://pay.google.com/about has a link header to  https://pay.google.com/gp/p/payment_method_manifest.json
1. Chrome performs `GET  https://pay.google.com/gp/p/payment_method_manifest.json`
    * https://pay.google.com/gp/p/payment_method_manifest.json is a JSON file with `"default_applications": ["https://pay.google.com/gp/p/web_manifest.json"]`.
1. Chrome performs `GET  https://pay.google.com/gp/p/web_manifest.json`.

**Comment by arturjanc** [comment]
For the purposes of `Sec-Fetch-Site` I think we have two options here:
1. Consider the party that controls the fetched URL as the initiator. In your example this would be `Y.com`.
2. Handle this similarly to how [HTTP redirects are handled](https://w3c.github.io/webappsec-fetch-metadata/#redirects). That is, compare the fetched URL to both `X.com` and `Y.com` and if it is cross-site to either of them, set `Sec-Fetch-Site: cross-site`.

Option 1 seems simpler, but it could allow attackers who can host text or JSON files in a given origin to make requests to other URLs in that origin that would appear as `same-origin` (by forcing it to be loaded as a payment method manifest). I forget where we ultimately landed on the origin/site restrictions for the Payment Method Manifest API; is it scoped to be same-site or can you create a PaymentRequest or load a manifest cross-site?

**Comment by rsolomakhin** [comment]
> I forget where we ultimately landed on the origin/site restrictions for the Payment Method Manifest API; is it scoped to be same-site or can you create a PaymentRequest or load a manifest cross-site?

The first HEAD request can have up to 3 same-site redirects, but the GET requests must be same-origin.

**Comment by rsolomakhin** [comment]
To clarify a little bit:

1. Merchant `x.com` creates a `PaymentRequest(y.com)`.
      * Allowed.
1. Chrome makes a HEAD request for `y.com`, which redirects to `sub.y.com`.
      * Allowed because it's same site and less than 3 redirects so far.
      * Different site or more than 3 redirects would not be allowed.
1. `sub1.y.com` has a link header to `sub1.y.com/file.json`. Chrome GETs it.
      * Allowed because it's same-origin.
      * Different origin would not work.
1. `sub1.y.com/file.json` contains the URL `sub1.y.com/another-file.json`. Chrome GETs it.
      * Allowed because it's same-origin.
      * Different origin would not work.

**Comment by arturjanc** [comment]
Hopefully @mikewest will double-check my reasoning here, but given the same-origin restrictions for fetching the JSON manifest files, we should be okay to treat the origin that serves the manifest as the `request_initiator` in your original question.

Here's what I think needs to happen for each request:
> 1/2. `x.com` creates a `PaymentRequest(y.com)` -> Chrome makes a HEAD request for `y.com`, which redirects to `sub.y.com`
* Each of these requests should set `site=cross-site`  because the original requester is cross-site and the HTTP redirect chain will follow the logic outlined in [§4.1](https://w3c.github.io/webappsec-fetch-metadata/#redirects).

> 3/4. `sub.y.com` has a link header to `sub.y.com/file.json` -> Chrome GETs `sub.y.com/file.json`.
* The request for `file.json` should have `site=same-origin` because its URL is controlled by `sub.y.com`. It would also be okay to treat `Y.com` as the initiator so that the request would be `site=same-site`.

> 5/6. `sub.y.com/file.json` contains the URL `sub.y.com/another-file.json` -> Chrome GETs `sub.y.com/another-file.json`
* As above, this should be `site=same-origin` because the URL is controlled by `sub.y.com`.

**Comment by mikewest** [comment]
I share @arturjanc's opinion. I think this also matches the relevant specifications, which set each request's `client` in step 4.1 of https://w3c.github.io/payment-method-manifest/#fetch-pmm. That then flows into the request's `origin` in step 1.2 of https://fetch.spec.whatwg.org/#fetching, and is used to set `Sec-Fetch-Site` in https://w3c.github.io/webappsec-fetch-metadata/#abstract-opdef-set-site.

**Comment by rsolomakhin** [comment]
cc @danyao

**Comment by mikewest** [comment]
As far as I can tell, this does't require any changes to Fetch Metadata, as both it and Payment Method Manifest seem to already say the right thing.
