### ISSUE TITLE
Decide on the proper `mode' value for CORS preflight requests

### ISSUE THREAD

**Issue by arturjanc** [w3c/webappsec-fetch-metadata#35]
Context: https://bugs.chromium.org/p/chromium/issues/detail?id=979946

Chrome's implementation currently doesn't set `Sec-Fetch-Mode` on CORS preflights (i.e.  OPTIONS requests). We should figure out what the expected `mode` for such requests is. To me it would make sense if their mode was `cors` since a preflight is part of CORS, but maybe this would be weird from Fetch's point of view?

@annevk @mikewest

**Comment by mikewest** [comment]
I agree that it might make sense from the developer's perspective for us to expose `cors` as the mode on the preflight request. I think this might put us into a loop given Fetch's algorithms (that is, HTTP fetch checks the CORS flag and kicks off a preflight, which goes through HTTP fetch and kicks off a preflight, which ...). @annevk probably knows off the top of his head whether that's accurate.

**Comment by annevk** [comment]
Per https://fetch.spec.whatwg.org/#cors-preflight-fetch-0 the mode is the default value, which is "no-cors", but given that this only invokes https://fetch.spec.whatwg.org/#concept-http-network-or-cache-fetch and that does not use mode for anything at the moment we could set it to "cors" I think.

**Comment by mikewest** [comment]
I noticed this morning that @arturjanc and team have added some conditionals to their server-side logic that triggers on Chrome 76's behavior of not sending `Sec-Fetch-Mode` with preflights. I feel some pressure to fix that in Chrome so it doesn't ossify/spread to other deployments.

If you're happy with `cors` as the mode, @annevk, then I'd like to run with that. I'm not sure this is exposed anywhere other than `Sec-Fetch-Mode` today (as preflights don't run through service workers?), but that should be testable via WPT.

I'll send you a PR shortly.

**Comment by annevk** [comment]
As I don't have authority the commit against whatwg/fetch didn't close this.

**Comment by mikewest** [comment]
Thanks!
