### ISSUE TITLE
`Sec-Fetch-Site` for requests from extension background pages

### ISSUE THREAD

**Issue by arturjanc** [w3c/webappsec-fetch-metadata#47]
(This is partly related to https://github.com/w3c/webappsec-fetch-metadata/issues/12 and was spurred by the discussion in https://chromium-review.googlesource.com/c/chromium/src/+/1903362)

Many browsers have extensions with a notion of a background page which executes scripts in its own origin, e.g. `chrome-extension://...`. These pages can load web content, in which case requests sent to the server hosting the resource need to attach `Sec-Fetch-*` headers. 

The question is what `site` value such requests should carry, with the complication being that some extensions may be granted explicit privileges to a given origin, so an extension may make both privileged and unprivileged requests. I think there are three options:

1. **Don't distinguish** privileged and unprivileged requests and always send the same `site` value, e.g. `none`.

2. Distinguish privileged and unprivileged requests and default to **treating requests from extensions as more trusted**:
- Send `none` for unprivileged requests.
- Send `same-origin` for privileged requests.

3. Distinguish privileged and unprivileged requests and default to **treating requests from extensions as less trusted**:
- Send `cross-site` for unprivileged requests.
- Send `none` for privileged requests.

My preference is (2) because (3) places a burden on web developers: they will see `cross-site` requests to their applications from users' extensions and -- in the absence of other information -- they will not be able to understand where the requests are coming from. Consequently, they will not be able to enforce security restrictions based on Fetch Metadata because blocking `cross-site` requests will appear to break their applications.

Browsers that provide information about requests sent from extensions (e.g. setting the `Origin` header to a value which identifies the extension) will still allow developers to reject such requests if they wish to do so;  given that malicious extensions are generally not in web developers' threat model and that there are significant deployability benefits of treating their requests as more trusted, I'd propose going with (2).

@mikewest @anforowicz @jerryzz0 @lweichselbaum

**Comment by anforowicz** [comment]
I prefer option 3, because:

- Option 3 seems more consistent with how extension background pages behave wrt to CORS:
    - Sending `Origin: extension://foo` for unprivileged requests.  This is the same behavior as if the request was initiated from another website and therefore I think this most closely maps to `Sec-Fetch-Site: cross-site`.
    - Sending no `Origin` header for unprivileged requests.  This is the same behavior as if the request was initiated by typing into an address bar (see "[Directly User-Initiated Requests](https://www.w3.org/TR/fetch-metadata/#directly-user-initiated)") and therefore I think this most closely maps to `Sec-Fetch-Site: none`.

- I don't understand why understanding the source of `Sec-Fetch-Site: cross-site` requests is more difficult in case of extension-initiated requests (compared to requests initiated by other websites).
    - For `cors` requests, web developers can observe `Origin: https://initiator.example.com` or `Origin: extension://initiator-example-extension` which helps *both* for website-initiators and unprivileged-extension-initiators
    - For `no-cors` requests, I wonder why the problem of identifying the initiator is less important for initiator-websites than for initiator-extensions - either way an unauthorized cross-site request is being made and the target-website has to make a choice whether to allow that VS to force the initiator-website and/or the initiator-extension to explicitly ask for permission (via CORS, or via extension permissions).

If option 3 is not acceptable, then is there another option where we introduce an extension-specific `Sec-Fetch-Site` value?  Maybe:

- Option 4: 
    - Sending `Sec-Fetch-Site: extension` (or `Sec-Fetch-Site: unprivileged-extension`?) for unprivileged requests from extensions
    - Sending either `Sec-Fetch-Site: none` or `Sec-Fetch-Site: same-origin` for privileged requests from extensions

**Comment by anforowicz** [comment]
@csreis

**Comment by mikewest** [comment]
> For `no-cors` requests, I wonder why the problem of identifying the initiator is less important for initiator-websites than for initiator-extensions - either way an unauthorized cross-site request is being made and the target-website has to make a choice whether to allow that VS to force the initiator-website and/or the initiator-extension to explicitly ask for permission (via CORS, or via extension permissions).

I see extensions as representing the Will of the User™, and as implicitly distinct from requests coming from websites, which represent something quite different. It would be unfortunate for developers to break extensions when enforcing security policies, and that seems to be the concern that's driving @arturjanc's suggestions here.

Artur: Do you have examples of extensions making requests against Google's servers that would break if you enforced the `cross-origin` restrictions y'all are considering? It would be interesting to evaluate the effect of forcing those extensions to request permission for `google.com` (which, of course, is substantially more capacious than just changing the `Sec-Fetch-Site` value.

While I recognize that extensions aren't exactly standardized, it would be helpful to broaden the audience here beyond Chromium's interpretation. @annevk: Can you hook us up with someone who has opinions about Mozilla's extension system? @ericlaw1979: Likewise for Edge? @johnwilander: Likewise for Safari?

**Comment by anforowicz** [comment]
> I see extensions as representing the Will of the User™ [...]

Well, what is "Will of the User™" when the user grants the extension permission to access and impersonate https://example.com, but nothing else?  In that case, I would expect that the extension can only bypass CORS (no `Origin` header) and send `Sec-Fetch-Site: none` in http requests to https://example.com, but not in requests to other websites.

> It would be unfortunate for developers to break extensions when enforcing security policies [...]

It would also be unfortunate for developers to break 3rd-party websites.  If it is indeed less fortunate to break extensions, then maybe we can let the web developers make the decision what to break - by distinguishing between `Sec-Fetch-Site: extension` (request from an unpermissioned extension) and `Sec-Fetch-Site: cross-site` (request from a cross-site website).

**Comment by mikewest** [comment]
> Well, what is "Will of the User™" when the user grants the extension permission to access and impersonate https://example.com, but nothing else? 

This is where I was hoping that @arturjanc could weigh in with regard to what would break if we ran with this behavior, and also ran with the cross-origin policies that his team is deploying. :)

> It would also be unfortunate for developers to break 3rd-party websites.

My claim here is that websites are governed by the same-origin policy, while extensions are not. :)

> by distinguishing between Sec-Fetch-Site: extension (request from an unpermissioned extension) and Sec-Fetch-Site: cross-site (request from a cross-site website).

This might be a reasonable answer. I'm really not thrilled about directly exposing that a request was made from an extension, but since we do that in the `Origin` header today...

**Comment by iVanlIsh** [comment]
Or maybe we could set `Sec-Fetch-SIte: cross-site` for non-privileged extension, `Sec-Fetch-Site: extension` ( or `same-site`? ) for privileged extension and `Sec-Fetch-Site: same-origin` for the source origin of the extension?

**Comment by arturjanc** [comment]
I didn't manage to dig into the data before the holidays, but I finally found some time to take a look, and my impression is that solving this may be more important than I originally thought. 

In a nutshell, just looking at unprivileged `cors` requests from background pages (these are the ones that send `Origin: chrome-extension://...`), it appears that across Google there are O(thousands) endpoints which get such traffic, and there are O(thousands) unique extensions which make such requests. Many of them seem like legitimate tools that have some reason to send such requests, and the majority of them succeed with a 200 status code.

The problem is that for `no-cors` requests we can't get such data because there's no way to distinguish unprivileged requests from extension background pages from webby cross-site requests (there is no `Origin` header in this case). So there's no way for developers to attribute these requests to extensions and exempt them from their Fetch Metadata logic; if any popular extension makes unprivileged requests to a bunch of domains, owners of these domains will not be able to adopt Fetch Metadata -- they'll see that they're blocking a certain number of incoming requests but won't know where these requests are coming from and whether this is breaking their application.

To solve the compatibility problem, I think we have three options:
- Do something along the lines of `Sec-Fetch-Site: extension` proposed by @anforowicz and @iVanlIsh.
  - This would work, but I'd be a little hesitant to do this because the `site` value was supposed to be a fairly broad bucket for requests outside of the control of websites. We're not distinguishing between requests made when clicking on a bookmark and typing the URL in the address bar, so I'm not sure if introducing a special value for extensions is consistent with the granularity we intend here, and it makes things more confusing for developers.
  - Alternatively, we could consider having a separate bit such as `Sec-Fetch-Ext: ?1` to convey the same information but without complicating the `site` value.
- Attach the `Origin` header to all unprivileged requests from extensions, i.e. add it also for requests in `no-cors` mode (while still setting `site=cross-site`).
  - This would let developers exempt extension-generated requests from their logic which blocks cross-site requests, at the cost of writing a bit of code.
  - There are some compatibility considerations here because a small number of websites break when they see requests with the `Origin` header, but this should be manageable in this context.
- Go with (2) from the original proposal, i.e. send `none` for unprivileged requests and `same-origin` for privileged ones.
  - This runs into the concerns we discussed above, but I'm still having a hard time understanding why we'd want to use this mechanism to start shifting the priority of constituencies to distrust extensions. Extensions, even those without permissions to any origin, already have significant power over the user and access to all extension APIs. My guess is that, even if we completely ignore the fact that any maliciously installed extension can give itself privileges for any origin, other extension APIs give a malicious extension author *much* more power than we would if we sent requests from background pages with `site=none`. Basically, I think avoiding this option introduces significant compatibility concerns for authors for little real security benefit.

**Comment by iVanlIsh** [comment]
After a brief talk via GVC with @arturjanc @jerryzz0 @rdcronin, we end up with a general idea shows as following:
1. No new value for `sec-fetch-site` or new header is going to be introduced for extensions.
2. All unprivileged requests will contain the `Origin` header and the `sec-fetch-site` will treat the request same as normal requests.
3. All privileged requests will be recognised as `sec-fetch-site:same-site`.

**Comment by annevk** [comment]
Could you write down the motivation as well?

**Comment by arturjanc** [comment]
It's definitely helpful to share the motivation, so I'll write down my understanding and rely on others to keep me honest :)

In a nutshell, we want to satisfy two goals which are somewhat at odds:
1. Avoid allowing requests from extensions which don't have permissions for a given site to send requests that bypass sites' Fetch Metadata logic. If an extension doesn't have access to a given URL, we'd like to treat it just as another website and mark the request as `cross-site`.
2. Allow developers to recognize requests made by extensions so they may exempt such requests from their Fetch Metadata enforcement. The main reason for this is that extensions can make "unexpected" requests to sites visited by their users, and if these requests are indistinguishable from web-based cross-site traffic, developers will see that their restrictions are affecting existing requests, and won't be able to start enforcing Fetch Metadata protections without fear of breakage. 
    * For example, let's say my application has an authenticated `/favicon.ico` that shows the number of unread email messages, and I want to protect from cross-origin information leaks by restricting it to only load same-origin. If a user has an extension that shows their frequently visited sites and their favicons, I may be comfortable responding with the favicon even though I'm restricting loads from other websites; at the very least least, it's helpful to know that requests incompatible with my Fetch Metadata restrictions are sent by an extension, as opposed to breaking legitimate functionality on other websites under my control.

Treating unpermissioned requests as `cross-site` but sending the `Origin` is safe by default (because they will be rejected by sites that protect their subresources from being loaded cross-site), but also gives application developers the information that lets them filter out extension-induced false positive violations of their Fetch Metadata logic.

Note that this requires sending the `Origin` header on all unpermissioned requests from extensions, including `no-cors` ones.

**Comment by arturjanc** [comment]
> 3. All privileged requests will be recognised as `sec-fetch-site: same-site`.

This should probably be `same-origin` rather than `same-site`. If we want to behave as if it's the application itself generated the request, `same-origin` is a better match, because some applications may want to only accept `same-origin` requests to protect themselves from attacks by other origins within the same site.

**Comment by annevk** [comment]
@arturjanc @iVanlIsh is the above what ended up shipping in Chrome?

**Comment by iVanlIsh** [comment]
@annevk yes, we do.
