### ISSUE TITLE
Header name "destination" may confuse developers

### ISSUE THREAD

**Issue by jugglinmike** [w3c/webappsec-fetch-metadata#51]
Today, this document defines a header named `Sec-Fetch-Dest` which maps to a property of a Fetch Request named "destination." This usage inverts the directionality which is commonly assigned to these terms, and it also reflects a difference in kind.

The word "destination" describes the recipient of a message. Which "end" of the communication depends on context. The new header value describes an aspect of the environment issuing the request, but in that context, "destination" refers to the environment *receiving* the message. For example, in the traffic initiated by `<img src=foo.gif>`, we would say the response (not the request) is "destined" for the image.

While replacing "destination" with an inverted term (e.g. "source") may be an improvement, it would still risk confusion with the network address with which requests are traditionally associated.

The Firefox developer tools describe a similar trait of requests using the term "cause."

![Screenshot of the "Network" tab in the Firefox developer tools](https://user-images.githubusercontent.com/677252/69987008-8dbd3680-150c-11ea-93b9-95ac23c77265.png)

That term seems preferable because it more accurately reflects the directionality and because it avoids conflation with network-address terminology. The longevity of Firefox's feature ([it was introduced three years ago](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/49)) suggests the term has intuitive meaning to developers (and leveraging the familiarity may hasten adoption).

**Comment by jugglinmike** [comment]
[WebKit and Chromium send the header `Purpose: prefetch` for requests initiated by `<link rel=prefetch>`](https://bugs.webkit.org/show_bug.cgi?id=46529) ([renamed from `X-Purpose`](https://bugs.webkit.org/show_bug.cgi?id=47802)), although security wasn't part of the motivation.

On the one hand, "purpose" sounds semantically accurate, so it may be another viable alternative to "destination." That said, [the new header value is currently expected to be "empty" in these cases](https://github.com/whatwg/fetch/blob/493c02127f49d6e9a4df5d56e2fcfa7fbaff48b2/fetch.bs#L1283-L1287), not "prefetch." This may be reason to avoid the term so Chromium and WebKit don't end up with request headers like

    Purpose: prefetch
    Sec-Fetch-Purpose: empty

**Comment by mikewest** [comment]
There's value in aligning with spec terminology. If @annevk is willing to change the term in Fetch, I'd be happy to align the header name with whatever we landed on.

That said, it's not clear to me that there's actually a problem here. As you note, the thing we're discussing is a property of the request, insofar as it reveals some context about the way in which the server's response will be used, e.g. the destination to which responses will flow. We could call that "purpose", or "cause", or "source", or "initiator", or "type", or "underlying-semantic-meaning", or any of a number of other terms.

> The Firefox developer tools describe a similar trait of requests using the term "cause."

Chrome's devtools have a similar "Type" field.

> WebKit and Chromium send the header Purpose: prefetch for requests initiated by <link rel=prefetch> 

We also send something for Service Worker: https://w3c.github.io/ServiceWorker/#service-worker-script-request. I'd like all of these to be folded into one mechanism rather than having three (cc @jakearchibald) 

> That said, the new header value is currently expected to be "empty" in these cases, not "prefetch."

We previously had much more detail in an earlier iteration of this approach that we called "context". When that shifted to "destination", much of the detail was dropped, keeping only that which was necessary for existing features (CSP mostly, AFAIR). I would not be at all sad if we added more granular destinations.

**Comment by annevk** [comment]
If someone is interested in digging up all the rationale for the existing naming and division of categories I'm happy to reconsider.

**Comment by mikewest** [comment]
Request's `context` introduced in https://github.com/whatwg/fetch/commit/3440a0a68a5f1576d75ed465d34bc8ee151ffacb.

Empty string `context` in https://github.com/whatwg/fetch/issues/29.

Compressed to `destination` in https://github.com/whatwg/fetch/issues/93 (lots of discussion).

Expanded in https://github.com/whatwg/fetch/commit/6b9cdaa9be7acd2b8074c74823981ef994d17857.

**Comment by annevk** [comment]
The third one there has type and destination (a much smaller set). So at some point we dropped type in favor of only destination.

**Comment by jugglinmike** [comment]
@annevk Found it: https://github.com/whatwg/fetch/issues/581, "Fold request type into destination." Does that close the loop?

**Comment by annevk** [comment]
Thanks, that indicates we already expose destination to developers through APIs. I don't think we should use a different header name therefore.

**Comment by jugglinmike** [comment]
@annevk Looking through [Preload](https://w3c.github.io/preload/), [SRI](https://w3c.github.io/webappsec-subresource-integrity/), [CSP](https://w3c.github.io/webappsec-csp/), [Mixed Content](https://w3c.github.io/webappsec-mixed-content/), and [Fetch](https://fetch.spec.whatwg.org), I was able to find one API: [`request.destination`](https://fetch.spec.whatwg.org/#dom-request-destination).

Did you see others?

Would redefinining `request.destination` to be an alias for a new `request.cause` be out of the question? We'd be introducing some cruft, but I'm wondering if that could be justified by evidence that the name "destination" is confusing.

**Comment by annevk** [comment]
That's the one. Is there evidence? @jakearchibald or @wanderview might know I suppose.

**Comment by jugglinmike** [comment]
No evidence that I'm aware of. The assumptions which motivated this issue are that developers haven't been exposed to this term very much and that they'll see it much more as we design more functionality around it. In addition to learning about Jake's and Ben's experiences, maybe we could poll.

**Comment by zcorpan** [comment]
I think aliases in general are bad. They can themselves be a source of confusion and bugs. They also usually don't make the old alias go away.

So I think the ideal would be a non-confusing accurate name and no aliases. But also I think there's value in not tweaking names after they have shipped in multiple browser engines.

**Comment by dveditz** [comment]
I'm not fond of the name `sec-fetch-dest` but `request.destination` has been supported broadly for at least a few years (https://developer.mozilla.org/en-US/docs/Web/API/Request/destination#Browser_compatibility). Makes sense for headers called `sec-fetch-` to line up with fetch terminology as much as possible, and renaming fetch properties just for the sake of naming doesn't make sense at this point. Too bad the name `request.context` got burned and ended up deprecated in the standards sausage-making, but that's where we are.

**Comment by jugglinmike** [comment]
> renaming fetch properties just for the sake of naming doesn't make sense at this point

Yeah, renaming is definitely out. My latest suggestion about aliasing was an attempt to prevent "destination" from propagating further (and to Simon's comment: I had no illusion about removing the request property from the platform). It doesn't look like there's sufficient interest to follow through on that, so I'll rescind.
