### ISSUE TITLE
Document still contains nested-document and nested-navigate

### ISSUE THREAD

**Issue by annevk** [w3c/webappsec-fetch-metadata#55]
With https://github.com/whatwg/fetch/pull/948 these are no longer needed, right?

**Comment by mikewest** [comment]
Thanks! Closing this out with https://github.com/w3c/webappsec-fetch-metadata/commit/d17bbaedbc743fc1a7c1d167b84b300dce07a4d1, but I apparently left https://github.com/whatwg/fetch/pull/948 hanging. Will try to remember what's left to do there.
