### ISSUE TITLE
Link to Editor's Draft should target actual spec

### ISSUE THREAD

**Issue by tidoust** [w3c/webappsec-fetch-metadata#57]
The [Editor's Draft link](https://github.com/w3c/webappsec-fetch-metadata/blob/master/index.bs#L8) should point to the actual draft (`https://w3c.github.io/webappsec-fetch-metadata/`), not to the GitHub repository.

**Comment by mikewest** [comment]
Closed in https://github.com/w3c/webappsec-fetch-metadata/pull/69.
