### ISSUE TITLE
Add `Sec-Fetch-Dest: json` for JSON Modules

### ISSUE THREAD

**Issue by petamoriken** [w3c/webappsec-fetch-metadata#87]
> A [request](https://fetch.spec.whatwg.org/#concept-request) has an associated destination, which is the empty string, "audio", "audioworklet", "document", "embed", "font", "frame", "iframe", "image", "json", "manifest", "object", "paintworklet", "report", "script", "serviceworker", "sharedworker", "style", "track", "video", "webidentity", "worker", or "xslt". Unless stated otherwise it is the empty string.

FYI: https://github.com/whatwg/html/pull/9486, https://github.com/whatwg/fetch/pull/1691

**Comment by annevk** [comment]
Maybe we should merge this specification into Fetch after all. It's not great if each time we update Fetch we also have to update this.

**Comment by mikewest** [comment]
The simplest thing to do seems to be decouple the explicit lists of valid header values by pointing to the relevant lists in Fetch. That is, something like the following for `Sec-Fetch-Dest`:

```diff
-Valid Sec-Fetch-Dest values include "audio", "audioworklet", "document", "embed", "empty", "font", "frame", "iframe", "image", "manifest", "object", "paintworklet", "report", "script", "serviceworker", "sharedworker", "style", "track", "video", "worker", "xslt".
+Valid Sec-Fetch-Dest values include the set of valid [=request=] [=request/destinations=] maintained in [[Fetch]].
```

That said, if someone would like to do the work to merge the documents, I don't have any problem with consolidation.

**Comment by miketaylr** [comment]
> The simplest thing to do seems to be decouple the explicit lists of valid header values by pointing to the relevant lists in Fetch. That is, something like the following for `Sec-Fetch-Dest`:

Good point, let me send in a PR.
